---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taa
  namespace: taa
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taa
  template:
    metadata:
      namespace: taa
      labels:
        app: taa
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: taa-php
        image: 226642452228.dkr.ecr.us-east-1.amazonaws.com/php-web:v1
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.2"
        # command: ["/bin/sh", "-c", "'source /config/taa-env'"]
        env:
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: taa-config
              key: APP_DEBUG
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: taa-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-config
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: taa-config
              key: DB_NAME   
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: taa-config
              key: DB_HOST
        ports:
        - containerPort: 9000
      - name: taa-nginx
        image: 226642452228.dkr.ecr.us-east-1.amazonaws.com/built-nginx:v1
        ports:
        - containerPort: 80
